spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://mysql:3306/paymentdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    web:
      exposure:
        include: "*"
payment:
  outbox:
    poll-delay-ms: 1000
    retry-delay-ms: 5000
    max-retry-delay-ms: 300000
    max-attempts: 5
    send-timeout-ms: 5000
    batch-size: 20
server:
  port: 8082
